spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    initialize: true
    url: jdbc:h2:mem:expense_tracker;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
    platform: h2
    mode: always
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
#      generate-ddl: true
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  h2:
    console:
      enabled: true